/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PokemonTCGPocketCardsV4Schema = {
  /**
   * Set prefix and padded card number (e.g., "a1-001").
   */
  id: string;
  /**
   * The printed name of the card.
   */
  name: string;
  /**
   * Rarity as a run of diamond or star characters, such as a single diamond or two stars. Promo cards read "Promo".
   */
  rarity: string;
  /**
   * The name of the pack the card is pulled from, not its identifier.
   */
  pack: string;
  /**
   * Hit points as a string. Trainer cards carry an empty string, since they have none.
   */
  health: string;
  /**
   * URL of the card artwork hosted in this repository.
   */
  image: string;
  /**
   * Whether the card is a full-art print, as "Yes" or "No".
   */
  fullart: string;
  /**
   * Whether the card is a Pokemon ex, as "Yes" or "No".
   */
  ex: string;
  /**
   * The illustrator credited on the card.
   */
  artist: string;
  /**
   * Energy type such as Water or Grass, or "Trainer" for trainer cards.
   */
  type: string;
}[];
