/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PokemonTCGPocketExpansionsV4Schema = {
  /**
   * Normalised lowercase set code (e.g., "a1").
   */
  id: string;
  /**
   * The expansion name as printed (e.g., "Genetic Apex").
   */
  name: string;
  /**
   * The packs that can be opened inside this expansion.
   */
  packs: {
    /**
     * Set prefix and pack slug (e.g., "a1-pikachu").
     */
    id: string;
    /**
     * The pack name as printed (e.g., "Pikachu").
     */
    name: string;
    /**
     * URL of the pack artwork in WebP format.
     */
    image: string;
    /**
     * URL of the pack artwork in PNG format.
     */
    image_png: string;
  }[];
}[];
