/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One record per printed card (3,879), the complement of the gameplay projection, without image URLs. Records are sparse: a field is omitted when it does not apply. The trading fields tradable, sharable and trade_cost are derived from rarity, shiny and art style, so every record carries tradable and sharable while trade_cost is null for non-tradable rarities.
 */
export type PokemonTCGPocketCardsV5CollectionNoImageSchema = {
  /**
   * Set prefix and padded card number (e.g., "a1-001").
   */
  id: string;
  /**
   * The printed name of the card.
   */
  name: string;
  /**
   * The normalised lowercase set code.
   */
  set_code: string;
  /**
   * The full name of the expansion the card belongs to.
   */
  set_name?: string;
  /**
   * The specific pack the card drops from, or the expansion name itself.
   */
  pack?: string;
  /**
   * The release date of the expansion, in ISO 8601 format.
   */
  release_date?: string;
  /**
   * The visual rarity indicator.
   */
  rarity: "◊" | "◊◊" | "◊◊◊" | "◊◊◊◊" | "☆" | "☆☆" | "☆☆☆" | "Crown Rare" | "Promo";
  /**
   * The cost to craft the card. Omitted for promos, which cannot be crafted.
   */
  pack_points?: number;
  /**
   * The visual treatment category (e.g., "Full Art", "Shiny", "Illustration Art"). Omitted when the card has none.
   */
  art_style?: string;
  /**
   * The credited artist of the card.
   */
  artist?: string;
  /**
   * The lore text printed on the card.
   */
  flavour_text?: string;
  /**
   * Prints from other sets mapping `set_code`, `set_name`, `id`, and `rarity`.
   */
  alternate_versions?: {
    /**
     * The normalised lowercase set code of the alternate print.
     */
    set_code: string;
    /**
     * The full name of the expansion of the alternate print.
     */
    set_name: string;
    /**
     * The card number within the alternate set.
     */
    id: number;
    /**
     * The visual rarity indicator of the alternate print.
     */
    rarity: string;
    [k: string]: unknown;
  }[];
  /**
   * True if the card is an "ex" rulebox Pokémon.
   */
  ex?: boolean;
  /**
   * True if the card is a Mega Evolution.
   */
  mega?: boolean;
  /**
   * True if the card is a shiny variant.
   */
  shiny?: boolean;
  /**
   * Tags like "ancient", "future", or "ultra_beasts". Present only when the card carries a tag.
   */
  special_tags?: string[];
  /**
   * True if the card can be traded with other players.
   */
  tradable: boolean;
  /**
   * True if the card can be sent as a wonder pick.
   */
  sharable: boolean;
  /**
   * The number of trading tokens required to trade for the card, or null when it is not tradable.
   */
  trade_cost?: number | null;
}[];
