/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Sparse projection: a field is omitted when it does not apply. A null value is dropped, and Trainer cards always omit ex and mega. Fossil items keep their playable stage, health and points.
 */
export type PokemonTCGPocketCardsV5CoreNoImageSchema = {
  /**
   * Set prefix and padded card number (e.g., "a1-001").
   */
  id: string;
  /**
   * The printed name of the card.
   */
  name: string;
  /**
   * The normalised lowercase set code.
   */
  set_code: string;
  /**
   * The specific pack the card drops from, or "Shared".
   */
  pack: string;
  /**
   * "Pokémon" or "Trainer".
   */
  type: string;
  /**
   * Energy type for Pokémon. Item classification for Trainers.
   */
  subtype: string;
  /**
   * Basic, Stage 1, or Stage 2. Present on Pokémon and on fossil items; omitted on other Trainers.
   */
  stage?: string;
  /**
   * The visual rarity indicator.
   */
  rarity: "◊" | "◊◊" | "◊◊◊" | "◊◊◊◊" | "Promo";
  /**
   * True if the card is an "ex" rulebox Pokémon. Present only on Pokémon; Trainer cards omit it.
   */
  ex?: boolean;
  /**
   * True if the card is a Mega Evolution. Present only on Pokémon; Trainer cards omit it.
   */
  mega?: boolean;
  /**
   * The maximum hit points. Present on Pokémon and on fossil items; omitted on other Trainers.
   */
  health?: number;
  /**
   * Points awarded to the opponent when knocked out. Present on Pokémon and on fossil items; omitted on other Trainers.
   */
  points?: number;
  /**
   * The internal integer used by the game client for deck rendering.
   */
  deckBuilderNr: number;
}[];
