/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PokemonTCGPocketCardsV5CoreSchema = {
  /**
   * Set prefix and padded card number (e.g., "a1-001").
   */
  id: string;
  /**
   * The printed name of the card.
   */
  name: string;
  /**
   * The normalised lowercase set code.
   */
  set_code: string;
  /**
   * The specific pack the card drops from, or "Shared".
   */
  pack: string;
  /**
   * "Pokémon" or "Trainer".
   */
  type: string;
  /**
   * Energy type for Pokémon. Item classification for Trainers.
   */
  subtype: string;
  /**
   * Basic, Stage 1, or Stage 2. Null for Trainers.
   */
  stage: string | null;
  /**
   * The visual rarity indicator.
   */
  rarity: string;
  /**
   * True if the card is an "ex" rulebox Pokémon.
   */
  ex: boolean;
  /**
   * True if the card is a Mega Evolution.
   */
  mega: boolean;
  /**
   * The maximum hit points. Null for Trainers.
   */
  health: number | null;
  /**
   * Points awarded to the opponent when knocked out. Null for Trainers.
   */
  points: number | null;
  /**
   * The internal integer used by the game client for deck rendering.
   */
  deckBuilderNr: number;
  /**
   * URL to the WEBP version of the card image.
   */
  image: string;
}[];
