/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PokemonTCGPocketCardsV5GameplaySchema = {
  /**
   * Set prefix and padded card number (e.g., "a1-001").
   */
  id: string;
  /**
   * The printed name of the card.
   */
  name: string;
  /**
   * The normalised lowercase set code.
   */
  set_code: string;
  /**
   * "Pokémon" or "Trainer".
   */
  type: string;
  /**
   * Energy type for Pokémon. Item classification for Trainers.
   */
  subtype: string;
  /**
   * Basic, Stage 1, or Stage 2. Null for Trainers.
   */
  stage: string | null;
  /**
   * The name of the required pre-evolution Pokémon.
   */
  evolves_from: string | null;
  /**
   * Tags like "ancient", "future", or "ultra_beasts". Defaults to null.
   */
  special_tags: string[] | null;
  /**
   * The maximum hit points. Null for Trainers.
   */
  health: number | null;
  /**
   * The energy cost to retreat. Null for Trainers.
   */
  retreat: number | null;
  /**
   * The energy type the Pokémon is weak to.
   */
  weakness: string | null;
  /**
   * Contains `exists` (boolean), `name` (string), and `effect` (string).
   */
  ability: {
    /**
     * True if the card has an ability.
     */
    exists: boolean;
    /**
     * The printed name of the ability.
     */
    name: string | null;
    /**
     * The mechanical effect text of the ability.
     */
    effect: string | null;
    [k: string]: unknown;
  };
  /**
   * Contains keys `1` and `2`. Each holds `cost`, `name`, `damage` (integer), and `effect` (string).
   */
  attacks: {
    "1": Attack;
    "2": Attack;
    [k: string]: unknown;
  };
  /**
   * The mechanical rules text for Trainer cards.
   */
  card_text: string | null;
  /**
   * Points awarded to the opponent when knocked out (1, 2, or 3).
   */
  points: number | null;
  /**
   * True if the card is an "ex" rulebox Pokémon.
   */
  ex: boolean;
  /**
   * True if the card is a Mega Evolution.
   */
  mega: boolean;
  /**
   * The internal integer used by the game client for deck rendering.
   */
  deckBuilderNr: number;
}[];

/**
 * A single attack on a Pokémon card.
 */
export interface Attack {
  /**
   * The energy cost symbols required to use the attack.
   */
  cost: string | null;
  /**
   * The printed name of the attack.
   */
  name: string | null;
  /**
   * The base damage value of the attack.
   */
  damage: number | null;
  /**
   * The additional effect text of the attack.
   */
  effect: string | null;
  [k: string]: unknown;
}
