/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Sparse projection: a field is omitted when it does not apply. A null value is dropped, and Trainer cards keep only the fields the game exposes on them. A non-Fossil Trainer keeps identity, subtype, card text and deck number; a Fossil item additionally keeps stage, health, points and weakness. Pokemon records keep the full combat projection.
 */
export type PokemonTCGPocketCardsV5GameplaySchema = {
  /**
   * Set prefix and padded card number (e.g., "a1-001").
   */
  id: string;
  /**
   * The printed name of the card.
   */
  name: string;
  /**
   * The normalised lowercase set code.
   */
  set_code: string;
  /**
   * "Pokémon" or "Trainer".
   */
  type: string;
  /**
   * Energy type for Pokémon. Item classification for Trainers.
   */
  subtype: string;
  /**
   * Basic, Stage 1, or Stage 2. Present on Pokémon and on fossil items; omitted on other Trainers.
   */
  stage?: string;
  /**
   * The name of the required pre-evolution Pokémon. Present only on Stage 1 and Stage 2 cards.
   */
  evolves_from?: string;
  /**
   * Tags like "ancient", "future", or "ultra_beasts". Present only when the card carries a tag.
   */
  special_tags?: string[];
  /**
   * The maximum hit points. Present on Pokémon and on fossil items; omitted on other Trainers.
   */
  health?: number;
  /**
   * The energy cost to retreat. Present on Pokémon; omitted on Trainers.
   */
  retreat?: number;
  /**
   * The energy type the Pokémon is weak to. Present on Pokémon that list a weakness and on fossil items, whose value is always "none"; omitted on other Trainers.
   */
  weakness?: string;
  /**
   * Present on Pokémon; omitted on Trainers. Contains `exists` (boolean), `name` (string), and `effect` (string).
   */
  ability?: {
    /**
     * True if the card has an ability.
     */
    exists: boolean;
    /**
     * The printed name of the ability.
     */
    name: string | null;
    /**
     * The mechanical effect text of the ability.
     */
    effect: string | null;
    [k: string]: unknown;
  };
  /**
   * Present on Pokémon; omitted on Trainers. Contains keys `1` and `2`. Each holds `cost`, `name`, `damage` (integer), and `effect` (string).
   */
  attacks?: {
    "1": Attack;
    "2": Attack;
    [k: string]: unknown;
  };
  /**
   * The mechanical rules text. Present on Trainer cards; omitted on Pokémon.
   */
  card_text?: string;
  /**
   * Points awarded to the opponent when knocked out (1, 2, or 3). Present on Pokémon and on fossil items; omitted on other Trainers.
   */
  points?: number;
  /**
   * True if the card is an "ex" rulebox Pokémon. Present only on Pokémon; Trainer cards omit it.
   */
  ex?: boolean;
  /**
   * True if the card is a Mega Evolution. Present only on Pokémon; Trainer cards omit it.
   */
  mega?: boolean;
  /**
   * The internal integer used by the game client for deck rendering.
   */
  deckBuilderNr: number;
}[];

/**
 * A single attack on a Pokémon card.
 */
export interface Attack {
  /**
   * The energy cost symbols required to use the attack.
   */
  cost: string | null;
  /**
   * The printed name of the attack.
   */
  name: string | null;
  /**
   * The base damage value of the attack.
   */
  damage: number | null;
  /**
   * The additional effect text of the attack.
   */
  effect: string | null;
  [k: string]: unknown;
}
