/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PokemonTCGPocketCardV5Schema = {
  id: string;
  name: string;
  set_code: string;
  set_name: string;
  pack: string;
  release_date: string | null;
  type: string;
  subtype: string;
  stage: string | null;
  evolves_from: string | null;
  rarity: string | null;
  pack_points: number | null;
  ex: boolean;
  mega: boolean;
  shiny: boolean;
  special_tags: string[] | null;
  art_style: string | null;
  health: number | null;
  retreat: number | null;
  weakness: string | null;
  ability: {
    exists: boolean;
    name: string | null;
    effect: string | null;
    [k: string]: unknown;
  };
  card_text: string | null;
  attacks: {
    "1": Attack;
    "2": Attack;
    [k: string]: unknown;
  };
  points: number | null;
  deckBuilderNr: number;
  share_code: string;
  artist: string | null;
  image: string;
  image_png: string;
  flavour_text: string | null;
  alternate_versions: {
    set_code: string;
    set_name: string;
    id: number;
    rarity: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}[];

export interface Attack {
  cost: string | null;
  name: string | null;
  damage: number | null;
  effect: string | null;
  [k: string]: unknown;
}
